# Generated by Django 4.2.1 on 2023-05-13 17:21

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('company_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TechnologiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='TypeOfProjModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Type of project',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('short_desc', models.CharField(max_length=100)),
                ('task_short', models.CharField(max_length=200)),
                ('solution_short', models.CharField(max_length=200)),
                ('logo_portfolio', models.FileField(upload_to='media')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.typeofprojmodel')),
                ('tech_stack', models.ManyToManyField(to='main.technologiesmodel')),
            ],
            options={
                'verbose_name_plural': 'Portfolio item',
            },
        ),
    ]
