# Generated by Django 4.2.1 on 2023-05-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
